### ISSUE TITLE
Additional comments

### ISSUE THREAD

**Issue by serdarbakirtas** [serdarbakirtas/EVCharging#1]
@dsk1306  I added screenshots to show the pixels and fonts. Design colors are taken from the brand guide so that colors may differ from the "JUCR iOS Challenge.pdf" file. The project has no button actions because I only focused on the design and animation implementation.
I would be happy to answer if you have any questions.  

Ready to review

**Comment by dsk1306** [comment]
Hi @serdarbakirtas,

Thanks for the update and the detailed description.

The task looks really nice and I don't have any additional questions. Now let me make a proper evaluation in our HR system and after that our HRs will contact you for next steps.

**Comment by serdarbakirtas** [comment]
Hi @dsk1306  As we talked about in the interview, I just want to let you know that there is a very small project that is related to the Observation framework and async/concurrency. This is additional but if you like feel free to take a look at it. 
[iOS_MVI](https://github.com/serdarbakirtas/iOS_MVI)
- Network/API folder -> related to async/concurrency
- Repositories folder -> Repository architecture
- Scenes/Profile -> MVI 

There is one more additional thing related to StateObject wrapped value: [StateObject wrappedValue](https://github.com/serdarbakirtas/AppleMusic/blob/release/AppleMusic/Scenes/SongList/SongsListView.swift)
This is old fashioned (old code), you can ignore it but just wanted to show how the StateObject(wrappedValue: ..) is implemented in business logic from view.

Thanks for your time.
